/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ctRZojL1TEX
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Bricolage_Grotesque } from 'next/font/google'

bricolage_grotesque({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
'use client'
import Link from "next/link"
import { Button } from "@/app/ui/button"
import { CardContent, Card } from "@/app/ui/card";
import { AvatarImage, AvatarFallback, Avatar } from "@/app/ui/avatar"

export default function RestrauntPage() {
  return (<>

    <section className="w-full bg-[#f8f9fa] py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div
          className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
          <img
            alt="Hero"
            className="mx-auto aspect-video overflow-hidden rounded-xl object-cover sm:w-full lg:order-last lg:aspect-square"
            height="550"
            src="/placeholder.svg"
            width="550" />
          <div className="flex flex-col justify-center space-y-4">
            <div className="space-y-2">
              <h1
                className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                Discover Discounted Meals Near You
              </h1>
              <p className="max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400">
                Our student-focused food app connects you with local eateries offering exclusive discounts. Enjoy
                delicious meals at affordable prices and build a sense of community.
              </p>
            </div>
            <div className="flex flex-col gap-2 min-[400px]:flex-row">
              <Link
                className="inline-flex h-10 items-center justify-center rounded-md bg-[#6c5ce7] px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-[#6c5ce7]/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#6c5ce7] disabled:pointer-events-none disabled:opacity-50 dark:bg-[#6c5ce7] dark:text-gray-50 dark:hover:bg-[#6c5ce7]/90 dark:focus-visible:ring-[#6c5ce7]"
                href="#">
                Get the App
              </Link>
              <Link
                className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 bg-white px-8 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-[#6c5ce7] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#6c5ce7] disabled:pointer-events-none disabled:opacity-50 dark:border-[#6c5ce7] dark:bg-[#1e1e1e] dark:hover:bg-[#2b2b2b] dark:hover:text-gray-50 dark:focus-visible:ring-[#6c5ce7]"
                href="#">
                Learn More
              </Link>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section className="w-full py-12 md:py-24 lg:py-32 bg-white dark:bg-[#1e1e1e]">
      <div className="container px-4 md:px-6">
        <div
          className="flex flex-col items-center justify-center space-y-4 text-center">
          <div className="space-y-2">
            <div
              className="inline-block rounded-lg bg-[#f8f9fa] px-3 py-1 text-sm dark:bg-[#2b2b2b]">
              Featured Restaurants
            </div>
            <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Explore Discounted Dining Options</h2>
            <p
              className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Our app connects you with local eateries offering exclusive discounts for students. Discover a diverse
              range of cuisines and dining experiences at affordable prices.
            </p>
          </div>
        </div>
        <div
          className="mx-auto grid max-w-5xl grid-cols-1 gap-6 py-12 sm:grid-cols-2 md:grid-cols-3 lg:gap-12">
          <Card>
            <img
              alt="Restaurant 1"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
              height="310"
              src="/placeholder.svg"
              width="550" />
            <CardContent className="p-4">
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="text-xl font-bold">Sushi Delight</h3>
                  <p className="text-gray-500 dark:text-gray-400">20% off all sushi rolls</p>
                </div>
                <Button size="sm" variant="outline">
                  Order Now
                </Button>
              </div>
            </CardContent>
          </Card>
          <Card>
            <img
              alt="Restaurant 2"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
              height="310"
              src="/placeholder.svg"
              width="550" />
            <CardContent className="p-4">
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="text-xl font-bold">Burger Bliss</h3>
                  <p className="text-gray-500 dark:text-gray-400">Buy one, get one free on all burgers</p>
                </div>
                <Button size="sm" variant="outline">
                  Order Now
                </Button>
              </div>
            </CardContent>
          </Card>
          <Card>
            <img
              alt="Restaurant 3"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
              height="310"
              src="/placeholder.svg"
              width="550" />
            <CardContent className="p-4">
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="text-xl font-bold">Pasta Paradise</h3>
                  <p className="text-gray-500 dark:text-gray-400">50% off all pasta dishes</p>
                </div>
                <Button size="sm" variant="outline">
                  Order Now
                </Button>
              </div>
            </CardContent>
          </Card>
          <Card>
            <img
              alt="Restaurant 4"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
              height="310"
              src="/placeholder.svg"
              width="550" />
            <CardContent className="p-4">
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="text-xl font-bold">Taco Fiesta</h3>
                  <p className="text-gray-500 dark:text-gray-400">Buy one, get one free on all tacos</p>
                </div>
                <Button size="sm" variant="outline">
                  Order Now
                </Button>
              </div>
            </CardContent>
          </Card>
          <Card>
            <img
              alt="Restaurant 5"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
              height="310"
              src="/placeholder.svg"
              width="550" />
            <CardContent className="p-4">
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="text-xl font-bold">Salad Sensation</h3>
                  <p className="text-gray-500 dark:text-gray-400">30% off all salad bowls</p>
                </div>
                <Button size="sm" variant="outline">
                  Order Now
                </Button>
              </div>
            </CardContent>
          </Card>
          <Card>
            <img
              alt="Restaurant 6"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
              height="310"
              src="/placeholder.svg"
              width="550" />
            <CardContent className="p-4">
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="text-xl font-bold">Curry Delight</h3>
                  <p className="text-gray-500 dark:text-gray-400">40% off all curry dishes</p>
                </div>
                <Button size="sm" variant="outline">
                  Order Now
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </section>
    <section className="w-full py-12 md:py-24 lg:py-32 bg-[#f8f9fa] dark:bg-[#2b2b2b]">
      <div className="container px-4 md:px-6">
        <div
          className="flex flex-col items-center justify-center space-y-4 text-center">
          <div className="space-y-2">
            <div
              className="inline-block rounded-lg bg-[#e6e6e6] px-3 py-1 text-sm dark:bg-[#3b3b3b]">
              Student Testimonials
            </div>
            <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">What Our Users Say</h2>
            <p
              className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Hear from our satisfied students about how our app has helped them discover delicious and affordable
              meals near their campus.
            </p>
          </div>
        </div>
        <div
          className="mx-auto grid max-w-5xl grid-cols-1 gap-6 py-12 sm:grid-cols-2 md:grid-cols-3 lg:gap-12">
          <Card>
            <CardContent className="p-6 text-left">
              <div className="flex items-center gap-4">
                <Avatar className="h-12 w-12 border">
                  <AvatarImage alt="@username" src="/placeholder-user.jpg" />
                  <AvatarFallback>JS</AvatarFallback>
                </Avatar>
                <div>
                  <h3 className="text-lg font-bold">Jessica Smith</h3>
                  <p className="text-gray-500 dark:text-gray-400">University of California, Berkeley</p>
                </div>
              </div>
              <p className="mt-4 text-gray-500 dark:text-gray-400">
                "This app has been a game-changer for me as a busy student. I love being able to discover new
                restaurants with discounts and save money on delicious meals. It's made eating out so much more
                affordable."
              </p>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-6 text-left">
              <div className="flex items-center gap-4">
                <Avatar className="h-12 w-12 border">
                  <AvatarImage alt="@username" src="/placeholder-user.jpg" />
                  <AvatarFallback>MR</AvatarFallback>
                </Avatar>
                <div>
                  <h3 className="text-lg font-bold">Michael Rodriguez</h3>
                  <p className="text-gray-500 dark:text-gray-400">University of Texas, Austin</p>
                </div>
              </div>
              <p className="mt-4 text-gray-500 dark:text-gray-400">
                "As a student, I'm always looking for ways to save money, and this app has been a lifesaver. The
                discounts and deals have helped me enjoy delicious meals without breaking the bank. I highly recommend
                it to all my friends."
              </p>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-6 text-left">
              <div className="flex items-center gap-4">
                <Avatar className="h-12 w-12 border">
                  <AvatarImage alt="@username" src="/placeholder-user.jpg" />
                  <AvatarFallback>EM</AvatarFallback>
                </Avatar>
                <div>
                  <h3 className="text-lg font-bold">Emily Martinez</h3>
                  <p className="text-gray-500 dark:text-gray-400">University of Washington, Seattle</p>
                </div>
              </div>
              <p className="mt-4 text-gray-500 dark:text-gray-400">
                "I love how this app connects me with local restaurants that offer discounts for students. It's helped
                me discover so many new and delicious places to eat, and the community aspect is really special. I
                feel like I'm part of a network of students who are all looking to save money and enjoy great food."
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    </section>
    <section className="w-full py-12 md:py-24 lg:py-32 bg-white dark:bg-[#1e1e1e]">
      <div className="container px-4 md:px-6">
        <div
          className="flex flex-col items-center justify-center space-y-4 text-center">
          <div className="space-y-2">
            <div
              className="inline-block rounded-lg bg-[#f8f9fa] px-3 py-1 text-sm dark:bg-[#2b2b2b]">
              Deal of the Day
            </div>
            <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Today's Top Discounted Meal</h2>
            <p
              className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Check out the amazing deal of the day and don't miss your chance to enjoy a delicious meal at a
              discounted price.
            </p>
          </div>
          <Card className="w-full max-w-3xl">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <img
                alt="Deal of the Day"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
                height="310"
                src="/placeholder.svg"
                width="550" />
              <div className="flex flex-col justify-center space-y-4 p-6">
                <div>
                  <h3 className="text-2xl font-bold">Sushi Extravaganza</h3>
                  <p className="text-gray-500 dark:text-gray-400">50% off all sushi rolls</p>
                </div>
                <div className="flex items-center justify-between">
                  <p className="text-2xl font-bold">$15.99</p>
                  <Button size="sm" variant="outline">
                    Order Now
                  </Button>
                </div>
              </div>
            </div>
          </Card>
        </div>
      </div>
    </section>
  </>);
};